### ISSUE TITLE
Check against i18n checklist for CR transition for wasm 2.0

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/spec#1806]
This short review is for is a request for transition for all 3 WebAssembly specifications, namely the [core](https://www.w3.org/TR/wasm-core-2/) spec, which defines the core code format and semantics;
the [JS API](https://www.w3.org/TR/wasm-core-2/) specification, which provides a JavaScript API for interacting with WebAssembly; and the [Web API](https://www.w3.org/TR/wasm-web-api-2/) specification, which describes the integration of WebAssembly with the broader web platform. 

All of the analysis herein concerns the changes made since Wasm 1.0. These are listed
[here](https://www.w3.org/TR/wasm-core-2/#release-20) and include the following extension
proposals:
Sign extension instructions; Non-trapping float-to-int conversions; multi-value block types and function results;
reference types, table instructions, and multiple tables; bulk memory and table instructions; SIMD vector instructions. Links to overviews of each proposal can be found in the proposal's respective github repo (these are listed [here](https://github.com/WebAssembly/proposals?tab=readme-ov-file)). 

Because WebAssembly is a code format designed to be produced and by compilers rather than humans, there is very little i18n interaction, especially in the diff since 1.0

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_ **ensure that there’s metadata about and support for basic things such as language and text direction**.  Also check the detailed guidance for [Language](https://www.w3.org/TR/international-specs/#resource) and [Text direction](https://www.w3.org/TR/international-specs/#text_direction).

    None of the new proposals contain any natural language text.
    - [x] Not applicable
    
2. [x] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._ **take into account the different typographic styles used around the world (for things such as line-breaking, text justification, emphasis or other text decorations, text selection and units, etc.)**  Also check the detailed guidance for [Typographic support](https://www.w3.org/TR/international-specs/#typography).

    
    - [x] Not applicable

3. [x] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._ **make allowances for the ways different scripts handle units of text**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    
    - [x] Not applicable

4. [x] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_ **understand the implications of normalisation, case folding, etc**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    - [x] Not applicable

5. [x] _If the spec (or its implementation) sorts text_ **ensure that it does so in locally relevant ways**. Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    - [x] Not applicable

6. [x] _If the spec (or its implementation) captures user input_ **ensure that it also captures metadata about language and text direction, and that it accommodates locale-specific input methods**. 

    - [x] Not applicable

7. [x] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_  **ensure that it will represent time as expected in locales around the world, and manage the relationship between local and global/absolute time**. Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).

    
    - [x] Not applicable

8. [x] _If the spec (or its implementation) allows any character encoding other than UTF-8._  **make sure you have a convincing argument as to why, and then ensure that the character encoding model is correct**.   Also check the detailed guidance for [Characters](https://www.w3.org/TR/international-specs/#characters).

    - [x] Not applicable

9. [x] _If the spec (or its implementation) defines markup_  **ensure support for internationalisation features and avoid putting human-readable text in attribute values or plain-text elements**.  Also check the detailed guidance for [Markup & syntax](https://www.w3.org/TR/international-specs/#markup).

    - [x] Not applicable

10. [x] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_  **ensure that the model is flexible enough to cope with wide variations in format, levels of data, etc**.   Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).

    - [x] Not applicable

11. [x] _If the spec (or its implementation) describes a format or data that is likely to need localization._  **ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc**.  

    - [x] Not applicable

12. [x] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_  **ensure that it can be adapted to suit different cultural norms around the world (ranging from depictions of people or gestures, to expectations about gender roles, to approaches to work and life, etc)**.

    - [x] Not applicable

Short i18n review checklist is [here](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist.html)

**Comment by xfq** [comment]
Thank you for doing the short self-review!

I took a brief look (not a complete review), and saw this:

>  If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers understand the implications of normalisation, case folding, etc. Also check the detailed guidance for Text-processing.

This is somewhat applicable, for example, see https://github.com/WebAssembly/spec/issues/1618

**Comment by dschuff** [comment]
True, somewhat applicable.
The wat syntax itself isn't used by browsers; browsers only support the wasm binary format, and that allows [names](https://www.w3.org/TR/wasm-core-2/#names%E2%91%A2) (which appear in JS as section names, import and export names) to be any UTF-8 encoded string. This was an asymmetry between the binary and text format that has since been fixed, as @rossberg indicated on #1618.
